In [2]:
import cv2
import matplotlib.pyplot as plt

import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
filtr = np.array([0,0,1,0,0])

In [5]:
np.convolve(arr, filtr)

array([0, 0, 1, 2, 3, 4, 5, 0, 0])

In [6]:
from scipy.signal import correlate

In [9]:
correlate(filtr, arr)

array([0, 0, 5, 4, 3, 2, 1, 0, 0])

In [15]:
np.correlate(arr, filtr, mode='full')

array([0, 0, 1, 2, 3, 4, 5, 0, 0])

In [16]:
impulse = np.array([
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,1,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
])

In [19]:
filtr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

In [23]:
from scipy.signal import convolve2d

In [29]:
convolve2d(impulse, filtr_2d)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 7, 8, 9, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [28]:
convolve2d(filtr_2d, impulse)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 7, 8, 9, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [30]:
from scipy.signal import correlate2d

In [31]:
correlate2d(impulse, filtr_2d)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 9, 8, 7, 0, 0],
       [0, 0, 6, 5, 4, 0, 0],
       [0, 0, 3, 2, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [32]:
correlate2d(filtr_2d, impulse)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 7, 8, 9, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])